version: "3"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/.yarn
      - /app/node_modules
      - ./:/app
    stdin_open: true
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/.yarn
      - /app/node_modules
      - ./:/app
    command: ["yarn", "test"]
